apiVersion: certmanager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: {{ .Values.letsencrypt.resourceGroupName }}
          subscriptionID: {{ .Values.letsencrypt.subscriptionID }}
          hostedZoneName: {{ .Values.letsencrypt.hostedZoneName }}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: {{ .Values.letsencrypt.clientID }}